-- Drop the table if it exists (to avoid 'already exists' and duplicate key errors)
IF OBJECT_ID('Worker', 'U') IS NOT NULL
    DROP TABLE Worker;
GO

-- Creating Worker Table with Constraints
CREATE TABLE Worker (
    WORKER_ID INT PRIMARY KEY,
    FIRST_NAME CHAR(25) NOT NULL,
    LAST_NAME CHAR(25),
    SALARY INT CHECK (SALARY BETWEEN 10000 AND 25000),
    JOINING_DATE DATETIME,
    DEPARTMENT CHAR(25) CHECK (DEPARTMENT IN ('HR', 'Sales', 'Accts', 'IT', 'Admin'))
);
GO

-- Inserting Sample Data
INSERT INTO Worker VALUES (1, 'Amitabh', 'Bachchan', 20000, '2016-06-11 00:00:00', 'HR');
INSERT INTO Worker VALUES (2, 'Satish', 'Kumar', 18000, '2014-02-19 00:00:00', 'Admin');
INSERT INTO Worker VALUES (3, 'Vipul', 'Verma', 22000, '2014-02-25 00:00:00', 'Admin');
INSERT INTO Worker VALUES (4, 'Ravi', 'Sharma', 24000, '2017-08-14 00:00:00', 'Sales');
INSERT INTO Worker VALUES (5, 'Alisha', 'Roy', 21000, '2018-01-09 00:00:00', 'IT');
GO

-- Q1
SELECT FIRST_NAME AS WORKER_NAME FROM Worker;

-- Q2
SELECT UPPER(FIRST_NAME) AS FIRST_NAME_UPPER FROM Worker;

-- Q3
SELECT DISTINCT DEPARTMENT FROM Worker;

-- Q4
SELECT SUBSTRING(FIRST_NAME, 1, 3) AS FIRST3CHARS FROM Worker;

-- Q5
SELECT CHARINDEX('a', FIRST_NAME) AS POSITION_OF_A 
FROM Worker 
WHERE FIRST_NAME = 'Amitabh';

-- Q6
SELECT RTRIM(FIRST_NAME) AS FIRST_NAME_RTRIM FROM Worker;

-- Q7
SELECT LTRIM(DEPARTMENT) AS DEPARTMENT_LTRIM FROM Worker;

-- Q8
SELECT DISTINCT DEPARTMENT, LEN(DEPARTMENT) AS DeptLength FROM Worker;

-- Q9
SELECT REPLACE(FIRST_NAME, 'a', 'A') AS FIRST_NAME_REPLACED FROM Worker;

-- Q10
SELECT FIRST_NAME + ' ' + LAST_NAME AS COMPLETE_NAME FROM Worker;

-- Q11
SELECT * FROM Worker ORDER BY FIRST_NAME ASC;

-- Q12
SELECT * FROM Worker ORDER BY FIRST_NAME ASC, DEPARTMENT DESC;

-- Q13
SELECT * FROM Worker WHERE FIRST_NAME IN ('Vipul', 'Satish');

-- Q14
SELECT * FROM Worker WHERE FIRST_NAME NOT IN ('Vipul', 'Satish');

-- Q15
SELECT * FROM Worker WHERE DEPARTMENT = 'Admin';

-- Q16
SELECT * FROM Worker WHERE FIRST_NAME LIKE '%a%';

-- Q17
SELECT * FROM Worker WHERE FIRST_NAME LIKE '%a';

-- Q18
SELECT * FROM Worker WHERE FIRST_NAME LIKE '_____h';

-- Q19
SELECT * FROM Worker WHERE SALARY BETWEEN 100000 AND 500000;

-- Q20
SELECT * FROM Worker 
WHERE MONTH(JOINING_DATE) = 2 AND YEAR(JOINING_DATE) = 2014;

-- Q21
SELECT COUNT(*) AS Admin_Count FROM Worker WHERE DEPARTMENT = 'Admin';
